TOOL_SYSTEM_PROMPT = '''You are an AI assistant that can call tools to assist with the user query.
After each tool call, you will receive a tool response within <tool_response></tool_response> tags.
- If the response indicates that the current user query has been fully solved, stop generating immediately and do not output any further text or tool calls.
- If the response shows an error, regenerate a tool call. This may involve calling the same tool with corrected arguments or a different tool, but do not repeat the exact same failed tool call without changes.
- If the response is successful but the query is not fully solved, you may need to call additional tools to complete the task.'''

TOOLS_TO_IGNORE = [
    'file_system-load_scenario',
    'file_system-pwd',
    'file_system-rm',
    'file_system-save_scenario',
    'math-absolute_value',
    'math-add',
    'math-divide',
    'math-imperial_si_conversion',
    'math-max_value',
    'math-min_value',
    'math-multiply',
    'math-percentage',
    'math-power',
    'math-round_number',
    'math-si_unit_conversion',
    'math-square_root',
    'math-subtract',
    'math-sum_values',
    'message-add_contact',
    'message-get_message_stats',
    'message-get_user_id',
    'message-list_users',
    'message-message_get_login_status',
    'message-message_login',
    'message-search_messages',
    'posting-authenticate_twitter',
    'posting-follow_user',
    'posting-get_tweet',
    'posting-get_tweet_comments',
    'posting-get_user_stats',
    'posting-get_user_tweets',
    'posting-list_all_following',
    'posting-posting_get_login_status',
    'posting-search_tweets',
    'posting-unfollow_user',
    'ticket-get_user_tickets',
    'ticket-logout',
    'ticket-ticket_get_login_status',
    'ticket-ticket_login',
    'trading-filter_stocks_by_price',
    'trading-get_order_history',
    'trading-get_symbol_by_name',
    'trading-get_transaction_history',
    'trading-notify_price_change',
    'trading-trading_get_login_status',
    'trading-trading_login',
    'trading-update_stock_price',
    'travel-get_all_credit_cards',
    'travel-get_budget_fiscal_year',
    'travel-travel_get_login_status',
    'vehicle-adjustClimateControl',
    'vehicle-get_current_speed',
    'vehicle-get_outside_temperature_from_google',
    'vehicle-get_outside_temperature_from_weather_com',
    'vehicle-pressBrakePedal',
    'vehicle-releaseBrakePedal'
]